### ISSUE TITLE
quick-start issue using github pages (cannot publish on branch master)

### ISSUE THREAD

**Issue by ftaruc** [yous/whiteglass-template#2]
I have followed the "Quick Start" tutorial for setting up this theme through github pages. However, the website fails in building and deploying from the following error: "Error: Cannot publish on branch master". 

This is a new repository and I followed step-by-step so I am not sure what the issue is. 

![image](https://user-images.githubusercontent.com/51760009/103839196-af5bec00-5043-11eb-9a9d-fa7e7957d510.png)

**Comment by yous** [comment]
The error message comes from this line of jekyll-action@2.0.4: https://github.com/helaili/jekyll-action/blob/2.0.4/entrypoint.sh#L88

I think it's because the name of your source branch is `master`. `*.github.io` repositories use `master` branch for generated HTML. Try renaming your current branch name to different one. Also I updated this template with 9bf5ca63f04d8623f263b264fee2c408c6ba41b2 and 25ff3ecd0b385a5b7802505c94ae1ed93fe0fbe3, so please consider applying them.

**Comment by ftaruc** [comment]
Thank you for the quick response! I applied the new changes to the template (by also removing Gemfile.lock), but am still running to an issue where the page doesn't load the content and is just whitespace.

The page now is built correctly, but I still receive this email even after inputting a personal token for "JEKYLL_PAT" in secrets.

![image](https://user-images.githubusercontent.com/51760009/103843758-424d5400-504d-11eb-8f23-5d2e1c6e8c4f.png)

If I am following your instructions correctly, I changed my source (or default branch) to this new branch called neo. Should I also change the following to neo, so it initializes properly when pushing new content?

![image](https://user-images.githubusercontent.com/51760009/103844184-2f874f00-504e-11eb-880b-d0e256b017da.png)


![image](https://user-images.githubusercontent.com/51760009/103843962-b38d0700-504d-11eb-934a-66864d12f159.png)


Sorry for all the questions, I am a new to all of this and I am just grateful for any assistance.

**Comment by yous** [comment]
That's right. Deployment should be triggered when there is a push to the source branch, so GitHub Actions should run on neo branch. I think I should change this repository's default branch name so HTML branch can be either `master` or `gh-pages`.

**Comment by ftaruc** [comment]
So after creating different repositories and trying over and over, I still am not able to get your theme working through github pages for my account: https://ftaruc.github.io/.

As you can see it's still white pages -- I am not sure what to do at this point. The site deploys correctly through Github's Actions:

![image](https://user-images.githubusercontent.com/51760009/103989733-02699800-5145-11eb-88ca-8a9b3a097df7.png)

I already attempted to deploy it through Travis CI through the manual setup, but it still doesn't work. I really love your theme, and I am not sure what I am doing wrong. If possible, can you look at my repository to see if there are any issues?

Is it possible that I am not updating my 'Secret' properly? 

![image](https://user-images.githubusercontent.com/51760009/103989953-51173200-5145-11eb-9b64-8e8beaa4ad8c.png)

Thank you for all your help!

**Comment by ftaruc** [comment]
I forgot to also add that the website builds fine locally through: "bundle exec jekyll serve", so my issue is with GitHub Pages.

**Comment by yous** [comment]
I think it's because `baseurl` is set to `/whiteglass-template` in your `_config.yml`. Can you try with `baseurl: ""`?

**Comment by ftaruc** [comment]
I changed `baseurl` back to  `baseurl: ""` and unfortunately it still doesn't work. Not quite sure if this helps, but I still receive this automated error message when I deploy the website through this theme:

![image](https://user-images.githubusercontent.com/51760009/103992157-8d985d00-5148-11eb-90b2-92b4ab086d6f.png)

**Comment by yous** [comment]
It seems that GitHub Pages is still building pages based on `source` branch, so check the Settings tab of your repository:

<img width="728" alt="Screenshot 2021-01-08 17 34 16" src="https://user-images.githubusercontent.com/853977/103992642-c5021a80-51d7-11eb-93f2-945faea3de96.png">

I think `master` branch should be selected for your case.

**Comment by ftaruc** [comment]
Ah, I am so stupid. Thank you for sticking with me, and all your help! Issue is resolved.

**Comment by yous** [comment]
No problem! Thank you for using this theme. 😄
